FROM node:14.9.0-buster-slim

RUN set -ex; \
    apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y --no-install-recommends build-essential git && \
    useradd -ms /bin/bash app -d /home/app -G sudo -u 2000 -p "$(openssl passwd -1 Passw0rd)" && \
    mkdir -p /app && \
    chown app:app /app

EXPOSE 3000

USER app
WORKDIR /app

COPY "package*.json" ./

RUN npm install

COPY . ./

ENTRYPOINT ["/bin/bash"]
CMD ["-c", "npm start"]